### ISSUE TITLE
Unbinding listener during an event calling can be unsafe

### ISSUE THREAD

**Issue by fedyk** [tenry92/typed-event-emitter#4]
Here a simple demonstration:

```js
const { EventEmitter } = require("typed-event-emitter")

class Test extends EventEmitter {
  constructor() {
    super()
    this.onEvent = this.registerEvent()
  }
  
  emitEvent() {
    this.emit(this.onEvent)
  }
}

const test = new Test()

const listener1 = test.onEvent(function() {
  console.log("listener1")
  listener1.unbind()
})

const listener2 = test.onEvent(function() {
  console.log("listener2") // <-- this one won't be called
})

test.emitEvent()
```

Does anyone face this problem as well?

**Comment by tenry92** [comment]
Thanks for your feedback! I was able to reproduce it and I took the opportunity to refactor / update the code and also adding some unit tests, also covering this specific bug.

Background: when emitting an event, the code was iterating through an array of callbacks. It calls callback 1/2, then  it gets removed, and there is no 2/1, so other callback does not get called.

In the bug fix, when emitting an event, an internal copy of the original array is created.

Please note: if you unbind listener2 within listener1, the second callback will still be called at least once. This is intended behavior, since the (internal) order of callbacks should not affect whether the other callback will be called or not in this use case.

My update is a breaking change (when using TypeScript), it is now `registerEvent<[number]>()` rather than `registerEvent<(arg: number) => any>()`.

**Comment by fedyk** [comment]
Thanks for so fast reaction ❤️. I will try to test out changes next week.

As for copying the array with listener. You can consider to use `Set` for keeping callbacks. It is safe for similar loops:

```
const list = new Set([1, 2])

list.forEach(function(val) {
  list.delete(1);
  console.log(val)
})
```

**Comment by tenry92** [comment]
Thanks for the hint. In a `Set`, a value must be unique. That would mean, the same callback function can't be bound to the same event multiple times, as it is currently possible.

Question is, what would the user expect if they bind the same function twice?

I did a test with DOM event listeners to compare what they are doing: if you try to bind the same callback twice, it is simply ignored and still only called once on event.

What is your oppinion on that?

**Comment by fedyk** [comment]
I just checked `EventEmitter` from [`events` ](https://nodejs.org/api/events.html#events_class_eventemitter). It has a similar behavior as the DOM event emitter you described above.

For the sake of simplicity and consistency, `Set` is a better fit than `Array`

**Comment by tenry92** [comment]
Thanks for your feedback! :) I think I'll change the behavior then. Would be another breaking change, so it would probably become version 4.0 then.
